export function getMediaUrl(url: string | undefined | null): string | undefined {
  if (!url) return undefined;
  return url; // Cloudinary returns absolute secure URLs, so we just pass it through!
}

export async function uploadFile(file: File) {
  try {
    // 1. Get Cloudinary signature from our backend
    const res = await fetch('/api/upload', {
      method: 'POST'
    });
    
    if (!res.ok) throw new Error('Failed to get upload signature');
    
    const { signature, timestamp } = await res.json();
    
    // 2. Upload directly to Cloudinary
    const cloudName = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
    const apiKey = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
    
    if (!cloudName || !apiKey) {
      console.error('Cloudinary environment variables are missing');
      return null;
    }

    const formData = new FormData();
    formData.append('file', file);
    formData.append('api_key', apiKey);
    formData.append('timestamp', timestamp);
    formData.append('signature', signature);
    
    // auto/upload detects if it's an image or video
    const uploadRes = await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/auto/upload`, {
      method: 'POST',
      body: formData
    });
    
    if (!uploadRes.ok) throw new Error('Failed to upload file to Cloudinary');
    
    const data = await uploadRes.json();
    return data.secure_url; // Return the absolute URL generated by Cloudinary
  } catch (error) {
    console.error("Upload error:", error);
    return null;
  }
}
